DocRede/src/br/ifrn/cm/docrede/controllers/ComputadorMBean.java
package br.ifrn.cm.docrede.controllers;

import javax.ejb.EJB;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ManagedProperty;
import javax.faces.bean.SessionScoped;
import javax.faces.model.DataModel;
import javax.faces.model.ListDataModel;

import br.ifrn.cm.docrede.dominio.Computador;
import br.ifrn.cm.docrede.dominio.TipoComputador;
import br.ifrn.cm.docrede.negocio.ComputadorService;
import br.ifrn.cm.docrede.negocio.ServidorService;

@ManagedBean
@SessionScoped
public class ComputadorMBean {
	
	private Computador computador;
	private boolean isNotebook;
	private DataModel<Computador> computadorModel;
	private boolean editarDesativado;
	
	
	@EJB
	private ComputadorService computadorService;
	
	
	@ManagedProperty(value="#{servidorMBean}")
	private ServidorMBean servidorMBean;
	
	@EJB
	private ServidorService servidorService;
	
	public ComputadorMBean() {
		computador = new Computador();
	}

	public Computador getComputador() {
		return computador;
	}

	public void setComputador(Computador computador) {
		this.computador = computador;
	}

	public DataModel<Computador> getComputadorModel() {
		return computadorModel;
	}

	public void setComputadorModel(DataModel<Computador> computadorModel) {
		this.computadorModel = computadorModel;
	}
	
	public String formComputador() {
		computador = new Computador();
		editarDesativado = false;
		return "/paginas/equipamento/computador/form.jsf";
	}
	
	public String listarComputador() {
		computadorModel = new ListDataModel<Computador>(computadorService.listar());
		return "/paginas/equipamento/computador/list.jsf";
	}

	public boolean isNotebook() {
		if(computador.getTipo() != TipoComputador.NOTEBOOK) {
			isNotebook = false;
		}
		else {
			isNotebook = true;
		}
		return isNotebook;
	}

	public void setNotebook(boolean isNotebook) {
		this.isNotebook = isNotebook;
	}
	
	public String salvar() {
		if(isNotebook) {
			computador.setTipo(TipoComputador.NOTEBOOK);
		}
		else {
			computador.setTipo(TipoComputador.DESKTOP);
		}
		
		computadorService.salvarOuAtualizar(computador);
		return formComputador();
	}
	
	public String ver() {
		computador = computadorModel.getRowData();
		if(computador.getTipo().equals(TipoComputador.SERVIDOR)) {
			servidorMBean.setServidor(servidorService.getByComputador(computador));
			servidorMBean.setEditarDesativado(true);
			return "/paginas/equipamento/computador/servidor/form.jsf";
		}
		else {
			editarDesativado = true;
			return "/paginas/equipamento/computador/form.jsf";
		}
	}
	
	public String deletar() {
		computadorService.remover(computadorModel.getRowData());
		return "/paginas/equipamento/computador/list.jsf";
	}
	
	public String editar() {
		editarDesativado = false;
		return null;
	}

	public ServidorMBean getServidorMBean() {
		return servidorMBean;
	}

	public void setServidorMBean(ServidorMBean servidorMBean) {
		this.servidorMBean = servidorMBean;
	}

	public boolean isEditarDesativado() {
		return editarDesativado;
	}

	public void setEditarDesativado(boolean editarDesativado) {
		this.editarDesativado = editarDesativado;
	}
}

DocRede/WebContent/paginas/equipamento/computador/form.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:b="http://bootsfaces.net/ui"
	template="/templates/template.xhtml">

	<ui:define name="conteudo">
		<H1>Formulário de Computador</H1>
		<b:messages />
		<b:form>
			<b:row>
				<b:column col-sm="4" col-xs="12">
				<b:inputText label="Patrimônio" type="number" required-message="Insira um patrimônio" value="#{computadorMBean.computador.equipamento.patrimonio}" disabled="#{computadorMBean.editarDesativado}" />
				</b:column>
				
				<b:column col-sm="8" col-xs="12">
					<b:inputText label="Serial" value="#{computadorMBean.computador.equipamento.serialNumber}" disabled="#{computadorMBean.editarDesativado}" />
				</b:column>
			</b:row>
			
			<b:row>
				<b:column col-sm="6" col-xs="12">
					<b:inputText label="Modelo" value="#{computadorMBean.computador.equipamento.modelo}" disabled="#{computadorMBean.editarDesativado}" />
				</b:column>
				
				<b:column col-sm="6" col-xs="12">
					<b:inputText label="Marca" value="#{computadorMBean.computador.equipamento.marca}" disabled="#{computadorMBean.editarDesativado}" />
				</b:column>
			</b:row>
			
			<b:row>
				<b:column col-sm="6" col-xs="12">
					<b:inputText label="Prédio" value="#{computadorMBean.computador.equipamento.predio}" disabled="#{computadorMBean.editarDesativado}" />
				</b:column>
				
				<b:column col-sm="6" col-xs="12">
					<b:inputText label="Sala" value="#{computadorMBean.computador.equipamento.sala}" disabled="#{computadorMBean.editarDesativado}" />
				</b:column>
			</b:row>
			
			<b:row>
				<b:column col-xs="6" col-sm="4">
					<b:datepicker label="Data de Compra" value="#{computadorMBean.computador.equipamento.dataCompra}" disabled="#{computadorMBean.editarDesativado}" />
				</b:column>
				
				<b:column col-xs="6" col-sm="4">
					<b:datepicker label="Data de Substituição" value="#{computadorMBean.computador.equipamento.dataSubstituicao}" disabled="#{computadorMBean.editarDesativado}" />
				</b:column>
				
				<b:column col-xs="12" col-sm="4">
					<b:inputText label="Garantia" type="number" value="#{computadorMBean.computador.equipamento.garantia}" disabled="#{computadorMBean.editarDesativado}" >
						<f:facet name="append">
							<h:outputText value="Anos" />
						</f:facet>
					</b:inputText>
				</b:column>
			</b:row>
						
			<b:row>
				<b:column col-sm="5" col-xs="12">
					<b:inputText label="Nome" value="#{computadorMBean.computador.nome}" disabled="#{computadorMBean.editarDesativado}" />
				</b:column>
				
				<b:column col-sm="5" col-xs="10">
					<b:inputText label="SO" value="#{computadorMBean.computador.sistemaOperacional}" disabled="#{computadorMBean.editarDesativado}" />
				</b:column>
				
				<b:column col-xs="2">
					<b:switch off-text="NÃO" on-text="SIM" label="Notebook"  value="#{computadorMBean.notebook}" disabled="#{computadorMBean.editarDesativado}" />
				</b:column>
			</b:row>
			
			<b:row>
				<b:column col-lg="12">
					<b:commandButton look="primary" icon="save" value="Salvar" action="#{computadorMBean.salvar}" rendered="#{computadorMBean.editarDesativado == false}" />
					<b:commandButton look="primary" icon="edit" value="Editar" action="#{computadorMBean.editar}" rendered="#{computadorMBean.editarDesativado}" />
					<b:commandButton icon="backward"  value="Voltar" action="#{computadorMBean.listarComputador}" />
				</b:column>
			</b:row>
		</b:form>
		
		
	</ui:define>
</ui:composition>

DocRede/WebContent/paginas/equipamento/computador/list.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:b="http://bootsfaces.net/ui"
	template="/templates/template.xhtml">

	<ui:define name="conteudo">
		<H1>Computadores</H1>
		
		<b:dataTable value="#{computadorMBean.computadorModel}" var="computador">
			<b:dataTableColumn>
				<f:facet name="header">Patrimônio</f:facet>
				<h:outputText value="#{computador.equipamento.patrimonio}" />
			</b:dataTableColumn>
			
			<b:dataTableColumn>
				<f:facet name="header">Tipo</f:facet>
				<h:outputText value="#{computador.tipo}" />
			</b:dataTableColumn>
			
			<b:dataTableColumn>
				<f:facet name="header">Marca</f:facet>
				<h:outputText value="#{computador.equipamento.marca}" />
			</b:dataTableColumn>
			
			<b:dataTableColumn>
				<f:facet name="header">Modelo</f:facet>
				<h:outputText value="#{computador.equipamento.modelo}" />
			</b:dataTableColumn>
			
			<b:dataTableColumn>
				<f:facet name="header">Sala</f:facet>
				<h:outputText value="#{computador.equipamento.sala}" />
			</b:dataTableColumn>
			
			<b:dataTableColumn>
				<f:facet name="header">Prédio</f:facet>
				<h:outputText value="#{computador.equipamento.predio}" />
			</b:dataTableColumn>
			
			<b:dataTableColumn>
				<f:facet name="header">SO</f:facet>
				<h:outputText value="#{computador.sistemaOperacional}" />
			</b:dataTableColumn>
			
			<b:dataTableColumn>
				<f:facet name="header">Opções</f:facet>
				<h:form>
					<b:commandButton action="#{computadorMBean.ver}" iconAwesome="file-text" />
					<b:commandButton action="#{computadorMBean.deletar}" icon="trash" />
				</h:form>
			</b:dataTableColumn>
		</b:dataTable>
	</ui:define>
</ui:composition>